from typing import Any

from xhtml2pdf import pisa


class ReportService:
    def generate_report(self, scan_data: dict[str, Any], output_path: str) -> bool:
        """
        Generates a professional PDF security report from scan data.
        """
        score = scan_data.get("score", 0)
        dist = scan_data.get("severity_distribution", {})
        findings = scan_data.get("findings", [])
        project_name = scan_data.get("project_name", "Scan")

        # The real backend formula (engine/scoring.py), stated on the report so
        # the number can be reproduced instead of trusted.
        weights = ", ".join(
            f"{sev} {w}" for sev, w in
            [("CRITICAL", 10), ("HIGH", 7), ("MEDIUM", 4), ("LOW", 1)]
        )

        # HTML template for the PDF
        html_content = f"""
        <html>
        <head>
            <style>
                body {{ font-family: Helvetica, Arial, sans-serif; color: #333; margin: 40px; }}
                .header {{ text-align: center; border-bottom: 2px solid #444; padding-bottom: 20px; }}
                .score-box {{ text-align: center; margin: 30px 0; font-size: 24px; font-weight: bold; }}
                .severity-table {{ width: 100%; border-collapse: collapse; margin-bottom: 30px; }}
                .severity-table th, .severity-table td {{ border: 1px solid #ccc; padding: 10px; text-align: left; }}
                .severity-table th {{ background-color: #f2f2f2; }}
                .finding {{ margin-bottom: 20px; padding: 15px; border-left: 5px solid #ccc; background-color: #fafafa; }}
                .critical {{ border-left-color: #ef4444; }}
                .high {{ border-left-color: #f97316; }}
                .medium {{ border-left-color: #eab308; }}
                .low {{ border-left-color: #22c55e; }}
                .fix {{ margin-top: 8px; padding: 8px 12px; background-color: #f0fdf4; border: 1px solid #bbf7d0; font-size: 11px; }}
                .triage {{ font-size: 10px; color: #666; }}
                .formula {{ font-size: 10px; color: #777; text-align: center; margin-top: 12px; }}
                .footer {{ text-align: center; font-size: 12px; color: #777; margin-top: 50px; }}
            </style>
        </head>
        <body>
            <div class="header">
                <h1>Security Vulnerability Scan Report</h1>
                <p>Project Audit Results &mdash; {project_name}</p>
            </div>

            <div class="score-box">
                Overall Security Score: {score}/100
                <div class="formula">
                    score = 100 / (1 + risk / 25), weighted risk points: {weights}
                </div>
            </div>

            <h3>Severity Distribution</h3>
            <table class="severity-table">
                <tr><th>Severity</th><th>Count</th></tr>
                <tr><td>CRITICAL</td><td>{dist.get('CRITICAL', 0)}</td></tr>
                <tr><td>HIGH</td><td>{dist.get('HIGH', 0)}</td></tr>
                <tr><td>MEDIUM</td><td>{dist.get('MEDIUM', 0)}</td></tr>
                <tr><td>LOW</td><td>{dist.get('LOW', 0)}</td></tr>
            </table>

            <h3>Detailed Findings</h3>
            {"".join([
                f'<div class="finding {f["severity"].lower()}">'
                f'<b>{f["severity"]}</b>: {f["desc"]}<br/>'
                f'File: {f["file_path"]} (Line {f["line"]}) '
                f'<span class="triage">| Triage: {f.get("triage", "open").replace("_", " ")}'
                f'{" | " + f["cwe"] if f.get("cwe") else ""}</span>'
                f'<div class="fix"><b>Remediation:</b> {f.get("remediation", "No remediation guidance recorded.")}</div>'
                f'</div>'
                for f in findings
            ])}

            <div class="footer">
                Generated by Security Vulnerability Scanner (SVS)
            </div>
        </body>
        </html>
        """

        try:
            with open(output_path, "wb") as result_file:
                pisa_status = pisa.CreatePDF(html_content, dest=result_file)
            return not pisa_status.err
        except Exception as e:
            print(f"PDF Generation Error: {e}")
            return False
